version: "3.8"

services:
  mysql-server:
    image: mysql:8.0.22
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3360:3306"
  member-service:
    image: demo-blackfriday-member-service
    ports:
      - "8081:8080"
    depends_on:
      - mysql-server