version: "3.8"

services:
  mysql-server:
    image: mysql:8.0.22
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3360:3306"

  myredis:
    image: redis
    ports:
      - "6379:6379"

  cassandra-node-0:
    image: cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra-node-0
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter11
    ports:
      - "7000:7000" # 노드간 클러스터 내부 통신
      - "7001:7001" # 노드간 보안 통신에 사용
      - "9042:9042" # CQL 클라이언트와 통신
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 5